

//FrontPage
export const FETCH_FRONTPAGE_LIST = 'FETCH_FRONTPAGE_LIST';
export const RECEIVE_FRONTPAGE_LIST = 'RECEIVE_FRONTPAGE_LIST';
export const RESET_FRONTPAGE_STATE = 'RESET_FRONTPAGE_STATE';
